services:
  minecraft:
    ports:
      - "25565:25565"

    environment:
      - EULA=TRUE
      - PVP='TRUE'
      - MEMORY=2G
      - SPAWN_MONSTERS='true'

    image: itzg/minecraft-server

    container_name: minecraft

    tty: true
    stdin_open: true

    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data:
